### ISSUE TITLE
Personal_sign error

### ISSUE THREAD

**Issue by kreativeteksolutions** [crypto-com/deficonnect-monorepo#101]
I have been trying to sign using defi wallet but for some reason i keep running into issues. Anyone idea what I am doing wrong?

provider.request({
 "method": 'personal_sign',
 "params": [walletAdd,message]
});

for the record i can get it working with 

provider.request({
                    "method": 'eth_sign',
                    "params": [account[0],h ]
                });
                
 however the issue is i cant use ecrecover using that method of signing. any guidance would be appreciated!

**Comment by andy-bin-cn** [comment]
Hi, @kreativeteksolutions , can you give me more information:
1. platform: iOS | android | Extension
2. are you test on Mobile inApp Browser?
3. please give us a input value and expect result, such as `walletAdd` `message `

**Comment by kreativeteksolutions** [comment]
> Hi, @kreativeteksolutions , can you give me more information:
> 1. platform: iOS | android | Extension
> 2. are you test on Mobile inApp Browser?
> 3. please give us a input value and expect result, such as `walletAdd` `message `
> 

Hello thank you for responding so fast much appreciated.

1. Chrome extension is the issue. (Works fine using wallet connect and also works via app)
2. Just a regular browser works fine in a mobile app browser
3. Wallet address = your wallet address, message = sha3("message")

That's obviously an example. It would make no sense giving you my wallet info since you can't really use it or sign anything. Let me know if you have any questions if needed I can load up something so you can test it in my environment. Let me know if that's needed. Again thank you for the help and response

**Comment by andy-bin-cn** [comment]
Hi, @kreativeteksolutions.
you can try change the params order like this:
`message` should be the first parameter.
```
provider.request({
  "method": 'personal_sign',
  "params": [message, walletAdd]
});
```

you can find more detail on here: https://github.com/crypto-com/deficonnect-monorepo/wiki/Chrome-Extension-Wallet-Integration#personal_sign
