### ISSUE TITLE
After call difiConnector.provider.request will show blank popup

### ISSUE THREAD

**Issue by cloudshadow** [crypto-com/deficonnect-monorepo#122]
Lib: "@deficonnect/web3-connector": "2.0.3"
Browser: chrome  108.0.5359.124
My Code:
```
difiConnector?.provider
      .request({ method: 'eth_signTypedData_v4', params: [account, msgParams] })
      .then((result) => {
        console.log(result);
      })
      .catch((error) => {
         console.log(error);
      });
```

![image](https://user-images.githubusercontent.com/1182967/210517006-7ae10916-f4cc-4c21-a5d1-c1d031268944.png)

**Comment by JackFengShixuan** [comment]
@cloudshadow msgParams should be a json string that can be decode by JSON.parse
