### ISSUE TITLE
Navigator is not defined when using with web3-react and next.js

### ISSUE THREAD

**Issue by SahilAujla** [crypto-com/deficonnect-monorepo#47]
I'm getting the error: Navigator is not defined when using with web3-react and next.js.\

![image](https://user-images.githubusercontent.com/83442423/175184372-19066d0d-c723-4995-b036-52912119d705.png)

![image](https://user-images.githubusercontent.com/83442423/175184423-0526bbb6-d7a6-43bb-a81a-353fe067a7c9.png)

And apparently that "navigator" is in node_modules/deficonnect/dist/index.js

![image](https://user-images.githubusercontent.com/83442423/175184618-d3722cdf-474e-4ecd-a436-3efe63f9fdf5.png)

**Comment by andy-bin-cn** [comment]
Hi, @SahilAujla , do you use the SSR to rending the application?

**Comment by SahilAujla** [comment]
Yes @andy-bin-cn 

Metamask and Walletconnect work fine with SSR.

**Comment by andy-bin-cn** [comment]
@SahilAujla can you try to use our 2.0.1 version? we fixed this on V2.
